# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 720)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(180, 246, 216)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bank = QtWidgets.QPushButton(self.centralwidget)
        self.bank.setGeometry(QtCore.QRect(0, 60, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bank.setFont(font)
        self.bank.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.bank.setObjectName("bank")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 110, 1051, 501))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1051, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 32px;\n"
"font: \"Arial Black\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.client = QtWidgets.QPushButton(self.centralwidget)
        self.client.setGeometry(QtCore.QRect(150, 60, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.client.setFont(font)
        self.client.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.client.setObjectName("client")
        self.bamk_type = QtWidgets.QPushButton(self.centralwidget)
        self.bamk_type.setGeometry(QtCore.QRect(450, 60, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bamk_type.setFont(font)
        self.bamk_type.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.bamk_type.setObjectName("bamk_type")
        self.city = QtWidgets.QPushButton(self.centralwidget)
        self.city.setGeometry(QtCore.QRect(600, 60, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.city.setFont(font)
        self.city.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.city.setObjectName("city")
        self.Queries_button = QtWidgets.QPushButton(self.centralwidget)
        self.Queries_button.setGeometry(QtCore.QRect(820, 620, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Queries_button.setFont(font)
        self.Queries_button.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Queries_button.setObjectName("Queries_button")
        self.Workers_button = QtWidgets.QPushButton(self.centralwidget)
        self.Workers_button.setGeometry(QtCore.QRect(550, 620, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Workers_button.setFont(font)
        self.Workers_button.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Workers_button.setObjectName("Workers_button")
        self.Change_button = QtWidgets.QPushButton(self.centralwidget)
        self.Change_button.setGeometry(QtCore.QRect(10, 620, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Change_button.setFont(font)
        self.Change_button.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Change_button.setObjectName("Change_button")
        self.Delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.Delete_button.setGeometry(QtCore.QRect(280, 620, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Delete_button.setFont(font)
        self.Delete_button.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.Delete_button.setObjectName("Delete_button")
        self.credit = QtWidgets.QPushButton(self.centralwidget)
        self.credit.setGeometry(QtCore.QRect(300, 60, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.credit.setFont(font)
        self.credit.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.credit.setObjectName("credit")
        self.return_credit = QtWidgets.QPushButton(self.centralwidget)
        self.return_credit.setGeometry(QtCore.QRect(900, 60, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.return_credit.setFont(font)
        self.return_credit.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.return_credit.setObjectName("return_credit")
        self.credit_type = QtWidgets.QPushButton(self.centralwidget)
        self.credit_type.setGeometry(QtCore.QRect(750, 60, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.credit_type.setFont(font)
        self.credit_type.setStyleSheet("font-size: 16px;\n"
"font: \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(245, 245, 245)")
        self.credit_type.setObjectName("credit_type")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bank.setText(_translate("MainWindow", "Банки"))
        self.label_3.setText(_translate("MainWindow", "Вывод таблиц"))
        self.client.setText(_translate("MainWindow", "Клиенты"))
        self.bamk_type.setText(_translate("MainWindow", "Типы банков"))
        self.city.setText(_translate("MainWindow", "Города"))
        self.Queries_button.setText(_translate("MainWindow", "Режим запросов"))
        self.Workers_button.setText(_translate("MainWindow", "Редактирование акканутов"))
        self.Change_button.setText(_translate("MainWindow", "Добавить данные"))
        self.Delete_button.setText(_translate("MainWindow", "Удаление данные"))
        self.credit.setText(_translate("MainWindow", "Выданные кредиты"))
        self.return_credit.setText(_translate("MainWindow", "Возвраты кредитов"))
        self.credit_type.setText(_translate("MainWindow", "Виды кредитов"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
